# Generated by Django 6.0.5 on 2026-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
